{% set name = "iso_varying_string" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/everythingfunctional/{{ name }}/-/archive/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
  sha256: d3020e8b348b24766a9897d7bc1f01ef5e8975d03c98c6cb4889e38c9441b758

build:
  number: 0
  script:
    - set -ex  # [unix]
    - export FFLAGS="${FFLAGS} -fcoarray=single"  # [unix]
    - set FFLAGS=-fcoarray=single  # [win]
    - cmake ${CMAKE_ARGS} -DBUILD_SHARED_LIBS=ON -B_build -GNinja  # [unix]
    - cmake -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX% -DBUILD_SHARED_LIBS=ON -B_build -GNinja  # [win]
    - cmake --build _build
    - cmake --install _build

  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('fortran') }}  # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - cmake
    - ninja

test:
  commands:
    - test -f $PREFIX/lib/lib{{ name }}$SHLIB_EXT  # [unix]
    - test -f $PREFIX/include/{{ name }}.mod  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\{{ name }}.mod exit 1  # [win]

about:
  home: https://gitlab.com/everythingfunctional/iso_varying_string
  license: MIT
  license_file: LICENSE
  summary: Implementation of the Fortran ISO_VARYING_STRING module in accordance with the standard

extra:
  recipe-maintainers:
    - awvwgk
